module.exports = {
  content: [
    "./src/**/*.html",
    "./src/**/*.ts",
    "./src/**/*.tsx",
    "./src/**/*.css",
    "./src/**/*.less"
  ],

  // Whitelist selectors generated by css-modules
  whitelistPatterns: [/_.*$/],

  // Special characters used by Tailwind CSS
  defaultExtractor: content => content.match(/[\w-/:]+(?<!:)/g) || []
};
