on:
  pull_request:
  push:
    branches-ignore:
      - "gh-pages"
    tags-ignore:
      - "**"

name: Tests

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: install node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: install
        run: yarn install

      - name: test
        run: yarn test

  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: yarn run parcel src/index.html
          wait-on: http://localhost:1234
